from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('en/about_us/', views.about_us, name="about_us"),
    path('en/company_info/', views.company_info, name="company_info"),
    path('en/msg_from_top_management/', views.msg_from_top_management, name="msg_from_top_management"),
    path('en/management_philosophy/', views.management_philosophy, name="management_philosophy"),
    path('en/corporate_profile/', views.corporate_profile, name="corporate_profile"),
    path('en/about_our_business/', views.about_our_business, name="about_our_business"),
    path('en/organization/', views.organization, name="organization"),
    path('en/global_network/', views.global_network, name="global_network"),
    path('en/our_team/', views.our_team, name="our_team"),
    path('en/products/', views.products, name="products"),
    path('en/material_industry/', views.material_industry, name="material_industry"),
    path('en/aily_food_industry/', views.daily_food_industry, name="daily_food_industry"),
    path('en/automotive_and_commercial/', views.automotive_and_commercial, name="automotive_and_commercial"),
    path('en/medical/', views.medical, name="medical"),
    path('en/consulting/', views.consulting, name="consulting"),
    path('en/dx/', views.dx, name="dx"),
    path('en/careers/', views.careers, name="careers"),
    path('en/japan/', views.japan, name="japan"),
    path('en/overseas/', views.overseas, name="overseas"),
    path('en/apply_now/', views.apply_now, name="apply_now"),
    path('en/contact/', views.contact, name="contact"),
    path('jp/home_/', views.home_, name="home_"),
    path('jp/about_us_/', views.about_us_, name="about_us_"),
    path('jp/company_info_/', views.company_info_, name="company_info_"),
    path('jp/msg_from_top_management_/', views.msg_from_top_management_, name="msg_from_top_management_"),
    path('jp/management_philosophy_/', views.management_philosophy_, name="management_philosophy_"),
    path('jp/corporate_profile_/', views.corporate_profile_, name="corporate_profile_"),
    path('jp/about_our_business_/', views.about_our_business_, name="about_our_business_"),
    path('jp/organization_/', views.organization_, name="organization_"),
    path('jp/global_network_/', views.global_network_, name="global_network_"),
    path('jp/our_team_/', views.our_team_, name="our_team_"),
    path('jp/products/', views.products_, name="products_"),
    path('jp/material_industry_/', views.material_industry_, name="material_industry_"),
    path('jp/aily_food_industry_/', views.daily_food_industry_, name="daily_food_industry_"),
    path('jp/automotive_and_commercial_/', views.automotive_and_commercial_, name="automotive_and_commercial_"),
    path('jp/medical_/', views.medical_, name="medical_"),
    path('jp/consulting_/', views.consulting_, name="consulting_"),
    path('jp/dx_/', views.dx_, name="dx_"),
    path('jp/careers_/', views.careers_, name="careers_"),
    path('jp/japan_/', views.japan_, name="japan_"),
    path('jp/overseas_/', views.overseas_, name="overseas_"),
    path('jp/apply_now_/', views.apply_now_, name="apply_now_"),
    path('jp/contact_/', views.contact_, name="contact_"),


]